export const httpStatus = {
    http_message_ok: 'OK',
    http_status_ok: 200,
    http_message_created: 'Created',
    http_status_created: 201,
    http_message_accepted: 'Accepted',
    http_status_accepted: 202,
    http_message_no_content: 'No Content',
    http_status_no_content: 204,
    http_message_bad_request: 'Bad Request',
    http_status_bad_request: 400,
    http_message_unauthorized: 'Unauthorized',
    http_status_unauthorized: 401,
    http_message_forbidden: 'Forbidden',
    http_status_forbidden: 403,
    http_message_not_found: 'Not Found',
    http_status_not_found: 404,
    http_message_method_not_allowed: 'Method Not Allowed',
    http_status_method_not_allowed: 405,
    http_message_internal_server_error: 'Internal Server Error',
    http_status_internal_server_error: 500,
    http_message_conflict: 'Conflict',
    http_status_conflict: 409
  };