name: Deploy to server

on:
  push:
    branches:
      - main
  workflow_dispatch: # Trigger manual workflow runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
           if [ -z "$SSH_AUTH_SOCK" ]; then
            eval "$(ssh-agent -s)"
            ssh-add ${{ secrets.PRIVATE_KEY }}
           fi
           cd /root/vapingecommerce
           if ! git pull origin main; then
            echo "Error executing git pull. Workflow stopped."
            exit 1
           fi
           if ! git checkout main; then
            echo "Error executing checkout on main. Workflow stopped"
            exit 1
           fi
           if ! git reset --hard origin/main; then
            echo "Error executing git reset. Workflow stopped."
            exit 1
           fi
           if ! git status; then
            echo "Error executing git status. Workflow stopped."
            exit 1
           fi
           if ! pnpm install; then
            echo "Error trying to install dependencies. Workflow stopped."
            exit 1
           fi
           if ! pnpm prisma generate; then
            echo "Error trying to generate prisma. Workflow stopped."
            exit 1
           fi
           if ! pnpm run build; then
            echo "Error building application. Workflow stopped."
            exit 1
           fi
           if ! pm2 startOrRestart pm2.config.js; then
            echo "Error restarting pm2 instance. Workflow stopped."
            exit 1
           fi
           if ! pm2 save; then
            echo "Error trying to save pm2 instances. Workflow stopped."
            exit 1
           fi